# Generated by Django 5.2.7 on 2025-12-12 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OptCode'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OtpDate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='09196847193', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل معتبر نیست')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='UserCode'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='FullName')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='NationalCode')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='BirthDate')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='PhonNumber')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='PostalCode')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
