# Generated by Django 5.2.7 on 2025-12-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_affiliate',
            field=models.BooleanField(default=False, verbose_name='Affiliate User'),
        ),
    ]
