# Generated by Django 5.1.7 on 2025-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
