# Generated by Django 5.2 on 2025-05-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalspecification',
            options={'verbose_name': 'Technical Specification', 'verbose_name_plural': 'Technical Specifications'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='product/product_image/', verbose_name='Main Product Image'),
        ),
    ]
