# Generated by Django 5.2 on 2025-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='product/product_image/main_image/', verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/product_image/other_image/', verbose_name='Image'),
        ),
    ]
