# Generated by Django 5.2.1 on 2025-05-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
    ]
