# Generated by Django 5.2.7 on 2025-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Special Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_price',
            field=models.PositiveIntegerField(default=0, verbose_name='User Price'),
        ),
    ]
