# Generated by Django 5.2.7 on 2025-12-31 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='shared_links', to='products.product')),
            ],
        ),
    ]
