# Generated by Django 5.2.7 on 2026-01-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_sharedproductlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounts',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
