# Generated by Django 5.2.7 on 2026-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_discounts_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
